# Generated by Django 5.0.6 on 2024-07-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_rh_data_alter_rh_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.TextField()),
                ('data', models.DateField()),
                ('Estado_Civil', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='rh',
        ),
    ]
