# Generated by Django 5.0.6 on 2024-07-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_rename_categoria_funcionario_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('salarioBase', models.CharField(max_length=100)),
                ('requisitoDeformacao', models.CharField(max_length=100)),
            ],
        ),
    ]
