# Generated by Django 5.0.6 on 2024-07-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_cargos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='salarioBase',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
