# Generated by Django 5.0.6 on 2024-07-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_alter_cargos_salariobase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('contato', models.CharField(max_length=100)),
                ('endereco_numero', models.CharField(max_length=100)),
                ('endereco_estado', models.CharField(max_length=100)),
                ('endereco_cep', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recrutamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(max_length=100)),
                ('habilidades_tecnicas', models.CharField(max_length=100)),
                ('experiencia_profissional', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='cargos',
            old_name='requisitoDeformacao',
            new_name='requisito_formacao',
        ),
        migrations.RenameField(
            model_name='cargos',
            old_name='salarioBase',
            new_name='salario_base',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome',
            new_name='nome_completo',
        ),
    ]
