# Generated by Django 5.0.6 on 2024-07-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_candidato_recrutamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='endereco_cidade',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='endereco_rua',
            field=models.CharField(default=0.0004972650422675286, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='endereco_cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='endereco_estado',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='endereco_numero',
            field=models.CharField(max_length=5),
        ),
    ]
