# Generated by Django 5.0.6 on 2024-07-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_candidato_endereco_cidade_candidato_endereco_rua_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='data',
            new_name='data_nasicimento',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=-1900, max_length=14),
            preserve_default=False,
        ),
    ]
