# Generated by Django 5.0.6 on 2024-07-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_rename_data_funcionario_data_nasicimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='data_nasicimento',
            new_name='data_nascimento',
        ),
    ]
