# Generated by Django 5.0.6 on 2024-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_remove_recrutamento_escolaridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
